### PR TITLE
Always use double precision in btScalar.h.

### PR DESCRIPTION
**Pull request by david-german-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/bullet3/3)

### CODE REVIEW

**Comment by jamiesnape** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bullet3/3#-:-KRdPSMSBlCW7IyGfDLc:bnfp4nl)_

**Comment by billhoffman** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bullet3/3#-:-KRdZFGHRxKUhQ4yEIzn:bg7igk9)_

**Comment by RussTedrake** [comment]
It's true that we always use double precision, but it seems like a better goal is to respect the cmake logic and aim to have this pushed upstream so we stay in sync...

**Comment by jamiesnape** [comment]
Very much so. I have started upstream some earlier patches, e.g., bulletphysics/bullet3#786.

**Comment by jamiesnape** [comment]
(Note that upstream does respect the logic, it just could be done a little cleaner that makes it easier to integrate with other projects.)

**Pull request merged**
