### PR TITLE
Apply bullet pod patches

### PR DESCRIPTION
**Pull request by billhoffman**
@RussTedrake I think I have it right this time.

### CODE REVIEW

**Comment by billhoffman** [comment]
@RussTedrake if you look at the second commit it should match the patch as I added the .in file first with no changes, then did the diff.

**Comment by RussTedrake** [comment]
this one looks good to me.

**Comment by amcastro-tri** [comment]
@billhoffman: In [#2354](https://github.com/RobotLocomotion/drake/pull/2354) I propose a fix for [#1712](https://github.com/RobotLocomotion/drake/issues/1712). The problem was with a lidar model using Bullet for ray casting. It seems we could also fix the problem by changing a right now [hard coded tolerance](https://github.com/bulletphysics/bullet3/blob/master/src/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp#L76) in Bullet.
I see that in our own fork however we are defining a new set of tolerances [here](https://github.com/billhoffman/bullet3/blob/0c09a32a4f56a82008509f886ed83ffb22350627/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp#L43).

My questions for you are:
1. Why do wee need this fork instead of the original Bullet? is there a patch or fix in this fork?
2. If we do need this fork, could we have this [tolerance](https://github.com/billhoffman/bullet3/blob/0c09a32a4f56a82008509f886ed83ffb22350627/src/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp#L43) redefined to something else?

**Comment by billhoffman** [comment]
The changes can be seen here: https://github.com/bulletphysics/bullet3/compare/bulletphysics:master...RobotLocomotion:master.  I was not the author of the changes.  I just moved them from the previous patch that was being applied. @RussTedrake.  Prior to using a fork there were .diff files maintained, they were deleted here: https://github.com/RobotLocomotion/bullet-pod/commit/2dbc12c63006ab9940b1ea21e5e7f29255e70abb .  Seems like @avalenzu made the original patches: https://github.com/RobotLocomotion/bullet-pod/commit/eeea8562df5d917e598af51a614f8e657c5f0a93 

So, to answer your questions.  1. there are changes in this fork.  2. Seems like we could redefine the changes as long as it did not break existing code.

**Comment by amcastro-tri** [comment]
Thank you for your answer!. Redefining some of these constants could be an option. I have a question for you then: when experimenting with my local copy of Bullet (say for instance changing the value of a hard coded constant) executing `make` at the super build level so that Bullet gets re-compiled again reverts my changes. How can a avoid this from happening so I can compile my experimental changes? (and hopefully PR them here if they prove successful).

**Comment by billhoffman** [comment]
You should change the hash and repository that is pointed to here: https://github.com/RobotLocomotion/bullet-pod/blob/master/CMakeLists.txt#L25
and here:
https://github.com/RobotLocomotion/drake/blob/master/CMakeLists.txt#L152
Then you can point to your own fork of bullet-pod.  Alternatively do not run make from the top level of the super build.  cd into the bullet build tree and run make, and do the same for drake.

**Comment by amcastro-tri** [comment]
Thank you @billhoffman. I tried the second option and it did work.

**Pull request merged**
