### PR TITLE
Set MACOSX_RPATH

### PR DESCRIPTION
**Pull request by jamiesnape**
Successful non-POD build of Drake on OS X here:

https://drake-jenkins.csail.mit.edu/job/mac-clang-experimental/101/

PTAL @RussTedrake or @david-german-tri.

---

This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/bullet3/2)

### CODE REVIEW

**Comment by david-german-tri** [comment]
What's the reason for doing this?  Also, could you please try a Mac MATLAB build?

**Comment by jamiesnape** [comment]
> What's the reason for doing this?

If you look in the all POD Makefile you will see lots of rpath fixups.

**Comment by jamiesnape** [comment]
> Also, could you please try a Mac MATLAB build?

Scheduled.

**Comment by david-german-tri** [comment]
> If you look in the all POD Makefile you will see lots of rpath fixups.

I don't see anything rpath-related in the Makefile.  Are you referring to the CMakeLists.txt here? https://github.com/RobotLocomotion/bullet-pod/blob/f7cfcf6a24977b57dc832593743c770548799e45/CMakeLists.txt#L54

**Comment by jamiesnape** [comment]
Yes.

**Comment by david-german-tri** [comment]
And setting MACOSX_RPATH makes that logic unnecessary, because the RPATH will get prepended onto each dylib dependency automatically?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bullet3/2#-:-KR_5JUnVmxlfwVO2vm6:b-s0jnwi)_

**Comment by jamiesnape** [comment]
Yes: https://cmake.org/cmake/help/v3.5/prop_tgt/MACOSX_RPATH.html

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bullet3/2#-:-KR_5oftb1fYglaFK9hu:b-30pvec)_

**Comment by david-german-tri** [comment]
And it's not on by default because some builds may have CMP0042 off?

:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bullet3/2#-:-KR_7IeHgTUsZb3nEo32:b-ncak4j)_

**Comment by jamiesnape** [comment]
CMP0042 OLD, yes.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/bullet3/2#-:-KR_7h98hWO0WjjltUVV:b2xkl8h)_

**Pull request merged**
